import SwiftUI

extension Color {
    /// `Color(hex: 0x5B6CF0)` — sRGB, no string parsing.
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

/// Palette sampled from the onboarding frame in Figma.
enum ReziColor {

    // MARK: Sky

    /// The sky as a 3 x 4 mesh, read off the reference gradient: deep blue in
    /// the top-left, vivid blue across the top-right, softening through
    /// indigo and violet, into magenta along the bottom.
    ///
    /// Neighbouring cells are deliberately far apart in value. Motion in a
    /// gradient is only visible where the colours differ — a mesh of similar
    /// blues can be swirling hard and still look like a flat wall.
    ///
    /// Row order is top to bottom, each row left to right. Change these and
    /// the whole sky changes; nothing else references sky colours.
    // sky-mesh:begin — generated by scripts/sample-gradient.py, do not hand-edit
    static let skyMesh: [Color] = [
        // top
        Color(hex: 0x2E3A88), Color(hex: 0x294BAD), Color(hex: 0x2753C4),
        // upper middle
        Color(hex: 0x304A99), Color(hex: 0x3148A4), Color(hex: 0x3047AD),
        // lower middle
        Color(hex: 0x334090), Color(hex: 0x5746A3), Color(hex: 0x71429B),
        // bottom
        Color(hex: 0x26205D), Color(hex: 0x55327C), Color(hex: 0x733772)
    ]
    // sky-mesh:end

    /// Soft lights that drift across the sky on their own paths, over the
    /// mesh. These are what make the motion legible — the mesh alone moves
    /// large areas of similar colour, which the eye barely registers.
    ///
    /// Both are lifted from the gradient itself, so they brighten it rather
    /// than tinting it toward something that is not in the palette.
    static let skyLightCool = Color(hex: 0x3F6FD8)
    static let skyLightWarm = Color(hex: 0x8A4A9E)

    /// Corner colours for the pre-iOS-18 fallback, taken from the mesh.
    static let skyDeep = Color(hex: 0x2E3A88)
    static let skyBlue = Color(hex: 0x2753C4)
    static let skyIndigo = Color(hex: 0x3148A4)
    static let skyPurple = Color(hex: 0x71429B)
    static let skyMagenta = Color(hex: 0x733772)

    static let page = Color.white

    // MARK: Cards

    static let cardSurface = Color.white
    static let cardTitle = Color(hex: 0x101014)
    static let cardMeta = Color(hex: 0x8B8B93)
    static let cardDivider = Color(hex: 0xD8D8E0)

    // MARK: Score gauge

    static let gaugeTrack = Color(hex: 0xE9E9EE)
    /// 0–39
    static let scoreWeak = Color(hex: 0xE8604D)
    /// 40–69 — "Good"
    static let scoreGood = Color(hex: 0xE8A33D)
    /// 70+ — "Best"
    static let scoreBest = Color(hex: 0x35C26B)

    // MARK: Copy

    static let headline = Color(hex: 0x08080A)
    static let subhead = Color(hex: 0x64646E)

    // MARK: Stats panel

    /// The card wrapping both the stats row and the button.
    static let panelSurface = Color(hex: 0xF2F4F8)
    static let statValue = Color.black
    static let statLabel = Color.black

    // MARK: Actions

    static let accent = Color(hex: 0x4D70EB)
    static let accentPressed = Color(hex: 0x4162D2)
    static let onAccent = Color.white
    static let signInMuted = Color(hex: 0x9A9AA3)

    // MARK: Swipe affordances

    static let swipeApply = Color(hex: 0x35C26B)
    static let swipePass = Color(hex: 0xE8604D)
}
